numbers generator by Yevhen Sahach
mate-academy/js_task-numbers-generator pull request #47
Opened 2019-08-22 21:21 UTC by yevhen-sahach

2019-08-23 16:30 UTC, irenhh requested changes

2019-08-23 16:30 UTC, irenhh commented on src/createNumbersGenerator.js
> +  const nums = arguments.length > 1
add default values

2019-08-26 10:06 UTC, irenhh requested changes

2019-08-26 10:06 UTC, irenhh commented on src/createNumbersGenerator.js
> +    ? numbers.filter(elem => (elem >= min && elem < max))
`elem` -> `num`

2019-08-26 10:06 UTC, irenhh commented on src/createNumbersGenerator.js
> +    ? numbers.filter(elem => (elem >= min && elem < max))
you don't need this condition

2019-08-26 10:40 UTC, yevhen-sahach commented
I removed condition, but does it make sense to iterate input if there no min and max specified? I ask it because in case if our input array has huge amount of elements it will iterate through them and spend time instead of taking "ready to go" array

2019-08-26 16:43 UTC, irenhh commented
> I removed condition, but does it make sense to iterate input if there no min and max specified? I ask it because in case if our input array has huge amount of elements it will iterate through all of them and spend time instead of taking "ready to go" array

this makes sense, you can leave your version

2019-08-26 16:43 UTC, irenhh approved these changes

2023-01-14 15:25 UTC, closed without merging